theme: jekyll-theme-minimal
logo: RetroFW_320x240.png
title: "RetroFW"
description: "RetroFW is the currently supported firmware for the Retro Game RS-97, RG-300, LDK and original Retro Arcade Mini devices. It allows you to play a wide variety of consoles and computers thanks to numerous emulators available to it as well as a number of popular videogame ports."
